spring:
  application:
    name: zuul-server
  zipkin:
    enabled: true
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 3030


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: shenzhen
    service-url:
      zone-1: http://localhost:8761/eureka
    availability-zones:
      shenzhen: zone-1


management:
  endpoints:
    web:
      exposure:
        include: ["prometheus","health"]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: false
    tags:
      application: ${spring.application.name}

zuul:
  routes:
    sale-order-api:
      path: /order/**
      serviceId: "SALE-ORDER-API"
      strip-prefix: false
  sensitive-headers: ''
