language: java
cache:
  directories:
    - $HOME/.m2
os:
  - linux
script:
  - cp ./.travis.settings.xml $HOME/.m2/settings.xml && ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -s ./.travis.settings.xml
  - ./mvnw test && ./mvnw cobertura:cobertura
after_script:
  - bash <(curl -s https://codecov.io/bash)
