server:
  port: 8080
eureka:
  instance:
    metadata-map:
      zone: zone-1
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: shenzhen
    service-url:
      zone-1: http://localhost:8761/eureka
    availability-zones:
      shenzhen: zone-1
spring:
  application:
    name: sale-order-api
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ordertest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MySQL
      username: sa
      password:
      driver-class-name: ${spring.datasource.driver-class-name}
    driver-class-name: org.h2.Driver
  zipkin:
    enabled: true
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: false
    generate-ddl: true
  data:
    elasticsearch:
      cluster-name: sale-order
      cluster-nodes: 10.16.18.46:9300
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: http://10.16.18.46:9200

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus","health"]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: false
    tags:
      application: ${spring.application.name}



eventuatelocal:
  kafka:
    bootstrap:
      servers: 10.16.18.46:9092
  zookeeper:
    connection:
      string: 10.16.18.46:2181