spring:
  datasource:
    url: jdbc:h2:mem:test?Mode=MySQL
    driver-class-name: org.h2.Driver

crqs:
  enabled: true
  kafka:
    servers: 10.16.18.46:9092
eventuate:
  database:
    schema: article

eventuatelocal:
  aggregateStore:
    bootstrap:
      servers: 10.16.18.46:9092
  kafka:
    bootstrap:
      servers: 10.16.18.46:9092
  zookeeper:
    connection:
      string: 10.16.18.46:2181