version: '2'
services:
    eureka-server:
        container_name: eureka-server
        build:
            context: ./eureka-server
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "8761:8761"
    zipkin-server:
        container_name: zipkin-server
        depends_on:
            - eureka-server
        build:
            context: ./zipkin-server
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "9411:9411"
        env_file:
            - docker-compose.yml.env
    zuul-server:
        container_name: zuul-server
        depends_on:
            - eureka-server
        build:
            context: ./zuul-server
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "3030:3030"
        env_file:
            - docker-compose.yml.env
#    oauth2-server:
#        container_name: oauth2-server
#        build:
#            context: ./oauth2-server
#            dockerfile: ./src/main/docker/Dockerfile
#        ports:
#            - "8443:8443"
#        volumes:
#            - ./oauth2-server/docker/cacerts:/usr/local/openjdk-8/lib/security/cacerts
#            - ./oauth2-server/docker/cacerts:/usr/local/openjdk-8/lib/security/jssecacerts
#            - ./oauth2-server/docker/cas.properties:/etc/cas/config/cas.properties
#            - ./oauth2-server/docker/thekeystore:/etc/cas/thekeystore
#        env_file:
#            - docker-compose.yml.env
#        extra_hosts:
#            - buyou.me:10.16.18.150
networks:
    default:
        external:
            name: sale-parent
