version: '2'
services:
    sale-order-api:
        container_name: sale-order-api
        build:
            context: ./sale-order-api
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "8081:8080"
        env_file:
            - docker-compose.yml.env
    sale-pay-api:
        container_name: sale-pay-api
        build:
            context: ./sale-pay-api
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "8071:8080"
        env_file:
            - docker-compose.yml.env
    sale-credit-api:
        container_name: sale-credit-api
        build:
            context: ./sale-credit-api
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "8072:8080"
        env_file:
            - docker-compose.yml.env
    sale-page:
        container_name: sale-page
        depends_on:
            - sale-pay-api
            - sale-credit-api
            - sale-order-api
        build:
            context: ./sale-page
            dockerfile: ./src/main/docker/Dockerfile
        ports:
            - "8061:8080"
        env_file:
            - docker-compose.yml.env
networks:
    default:
        external:
            name: sale-parent
